name: Release
on: release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build APK
      run: flutter build apk --debug --split-per-abi
    - name: Release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/debug/*.apk"
        token: ${{ secrets.TOKEN }}
